In [1]:
import os
os.getcwd()

'C:\\Users\\91705\\Downloads\\ML_lab'

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("Heart.csv")

In [4]:
df.head()

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0           1   63    1       typical     145   233    1        2    150   
1           2   67    1  asymptomatic     160   286    0        2    108   
2           3   67    1  asymptomatic     120   229    0        2    129   
3           4   37    1    nonanginal     130   250    0        0    187   
4           5   41    0    nontypical     130   204    0        2    172   

   ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0      0      2.3      3  0.0       fixed   No  
1      1      1.5      2  3.0      normal  Yes  
2      1      2.6      2  2.0  reversable  Yes  
3      0      3.5      3  0.0      normal   No  
4      0      1.4      1  0.0      normal   No

In [5]:
df.shape  #rows, columns

(303, 15)

In [6]:
df.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [7]:
#datatype of each column
df.dtypes

Unnamed: 0      int64
Age             int64
Sex             int64
ChestPain      object
RestBP          int64
Chol            int64
Fbs             int64
RestECG         int64
MaxHR           int64
ExAng           int64
Oldpeak       float64
Slope           int64
Ca            float64
Thal           object
AHD            object
dtype: object

In [8]:
#find out zeros
df==0

Unnamed: 0    Age    Sex  ChestPain  RestBP   Chol    Fbs  RestECG  \
0         False  False  False      False   False  False  False    False   
1         False  False  False      False   False  False   True    False   
2         False  False  False      False   False  False   True    False   
3         False  False  False      False   False  False   True     True   
4         False  False   True      False   False  False   True    False   
..          ...    ...    ...        ...     ...    ...    ...      ...   
298       False  False  False      False   False  False   True     True   
299       False  False  False      False   False  False  False     True   
300       False  False  False      False   False  False   True     True   
301       False  False   True      False   False  False   True    False   
302       False  False  False      False   False  False   True     True   

     MaxHR  ExAng  Oldpeak  Slope     Ca   Thal    AHD  
0    False   True    False  False   True  False  False  
1    False  False    False  False  False  False  False  
2    False  False    False  False  False  False  False  
3    False   True    False  False   True  False  False  
4    False   True    False  False   True  False  False  
..     ...    ...      ...    ...    ...    ...    ...  
298  False   True    False  False   True  False  False  
299  False   True    False  False  False  False  False  
300  False  False    False  False  False  False  False  
301  False   True     True  False  False  False  False  
302  False   True     True  False  False  False  False  

[303 rows x 15 columns]

In [9]:
df[df==0].count()

Unnamed: 0      0
Age             0
Sex            97
ChestPain       0
RestBP          0
Chol            0
Fbs           258
RestECG       151
MaxHR           0
ExAng         204
Oldpeak        99
Slope           0
Ca            176
Thal            0
AHD             0
dtype: int64

In [10]:
df.columns

Index(['Unnamed: 0', 'Age', 'Sex', 'ChestPain', 'RestBP', 'Chol', 'Fbs',
       'RestECG', 'MaxHR', 'ExAng', 'Oldpeak', 'Slope', 'Ca', 'Thal', 'AHD'],
      dtype='object')

In [11]:
#mean
df['Age'].mean()

54.43894389438944

In [12]:
newdf=df[['Age','Sex','Thal']]  #labelbased slicing

In [13]:
#cross validation
from sklearn.model_selection import train_test_split

In [14]:
train,test=train_test_split(df,random_state=0,test_size=0.25)

In [15]:
train.shape

(227, 15)

In [16]:
test.shape

(76, 15)

In [2]:
import numpy as np

In [3]:
actual=list(np.ones(50))+list(np.zeros(50))
np.array(actual)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
predicted=list(np.ones(45))+list(np.zeros(55)) 
np.array(predicted)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
from sklearn.metrics import classification_report, confusion_matrix

In [6]:
print(classification_report(actual,predicted))
confusion_matrix(actual,predicted)

              precision    recall  f1-score   support

         0.0       0.91      1.00      0.95        50
         1.0       1.00      0.90      0.95        50

    accuracy                           0.95       100
   macro avg       0.95      0.95      0.95       100
weighted avg       0.95      0.95      0.95       100



array([[50,  0],
       [ 5, 45]], dtype=int64)

In [7]:
from sklearn.metrics import accuracy_score
accuracy_score(actual,predicted)

0.95